### Read articles of all authors (User role)
GET http://localhost:5000/user-api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDA1YzcwZjA2NzI4N2NjYzliNTE4YyIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzc4NDA4NTY2LCJleHAiOjE3Nzg0MTIxNjZ9.rYI2zzJkiK4x2JGZNzOc01QwL3B9r4zTggCo3lIClLY

### Add comments to articles (User role)
PUT http://localhost:5000/user-api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMDA1YzcwZjA2NzI4N2NjYzliNTE4YyIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzc4NDA4NTY2LCJleHAiOjE3Nzg0MTIxNjZ9.rYI2zzJkiK4x2JGZNzOc01QwL3B9r4zTggCo3lIClLY
Content-Type: application/json

{
    "articleId": "69b3a9e7e5d5192de030eb7f",
    "comment": "This article is useful"
}
